import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'hi', 'gu', 'es', 'zh_Hant', 'ar', 'fr', 'ru', 'ja', 'de'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? hiText = '',
    String? guText = '',
    String? esText = '',
    String? zh_HantText = '',
    String? arText = '',
    String? frText = '',
    String? ruText = '',
    String? jaText = '',
    String? deText = '',
  }) =>
      [
        enText,
        hiText,
        guText,
        esText,
        zh_HantText,
        arText,
        frText,
        ruText,
        jaText,
        deText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

/// Used if the locale is not supported by GlobalMaterialLocalizations.
class FallbackMaterialLocalizationDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      SynchronousFuture<MaterialLocalizations>(
        const DefaultMaterialLocalizations(),
      );

  @override
  bool shouldReload(FallbackMaterialLocalizationDelegate old) => false;
}

/// Used if the locale is not supported by GlobalCupertinoLocalizations.
class FallbackCupertinoLocalizationDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const FallbackCupertinoLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(FallbackCupertinoLocalizationDelegate old) => false;
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

bool _isSupportedLocale(Locale locale) {
  final language = locale.toString();
  return FFLocalizations.languages().contains(
    language.endsWith('_')
        ? language.substring(0, language.length - 1)
        : language,
  );
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // AdminLogin
  {
    'uvekgrzh': {
      'en': 'O systemie',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'uek37mb7': {
      'en': 'Pomoc',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'bsnmojw6': {
      'en': 'Kontakt',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'vmszlcqz': {
      'en': 'Kontrola zakładów \nwzajemnych online',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '2m8eatvu': {
      'en':
          'System analityczny do monitorowania i analizy zgodności operatorów zakładów wzajemnych online z przepisami prawa polskiego. Narzędzie przeznaczone wyłącznie dla uprawnionych pracoowników KAS.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'sqbtndq6': {
      'en': 'Zaloguj przez SSO',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '3y4kaj94': {
      'en': 'Login służbowy',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'xo2mvc9e': {
      'en': 'Hasło',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '60cjjzr2': {
      'en': 'Zaloguj',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '2ggde34d': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // Dashboard
  {
    '7mikddb5': {
      'en': 'Strona Główna',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'bbvplzyx': {
      'en': 'Skanuj Podmiot',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'im7rfgec': {
      'en': 'Historia Analiz',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'lv8qfuma': {
      'en': 'Ustawienia',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'xut4ymry': {
      'en': 'Pomoc',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'xosw0g8k': {
      'en': 'Wersja v1.0',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'ezh6ec1p': {
      'en': 'Szybki podgląd ryzyk',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'hfnoviuz': {
      'en': '12%',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'ck3nueo7': {
      'en': 'Niskie ryzyko',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'bzr83qd5': {
      'en': 'Wykryto ryzyko, sprawdź szczegóły.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'xaz5fmdr': {
      'en': 'Aktywne podmioty',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'wz6orbij': {
      'en': '19',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'w0l4hogm': {
      'en': 'Alerty',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '4syqm1c7': {
      'en': '2',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'thwk49f7': {
      'en': 'Ostatni skan:',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '4cnp6syc': {
      'en': '07.12.2025',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'a8as8hnl': {
      'en': 'Podmioty z listy MF',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '2dzqkvi7': {
      'en': 'Nazwa podmiotu',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '9n9flbce': {
      'en': 'Status',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'o4od72q7': {
      'en': 'Ostatni skan',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'qiwbzsse': {
      'en': 'Alerty',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '5phx9lw6': {
      'en': 'Szybki skan',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'uowzxd39': {
      'en':
          'Rozpocznij natychamiastową analizę wybranego podmiotu w celu weryfikacji zgodności',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'px3iqhz8': {
      'en': 'Rozpocznij teraz',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '07cc1e6n': {
      'en': 'System Monitorowania Zakładów Wzajemnych',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'xuepl8rh': {
      'en': 'Grzegorz Mazurkiewicz',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'og3gw0j0': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // Scan
  {
    'cv5tnlds': {
      'en': 'Strona Główna',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'q9jk8rt4': {
      'en': 'Skanuj Podmiot',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'je5aqics': {
      'en': 'Historia Analiz',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'xoe2qip0': {
      'en': 'Ustawienia',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '68acb6yh': {
      'en': 'Pomoc',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'y13pvbnv': {
      'en': 'Wersja v1.0',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '022bhhck': {
      'en': 'Skanuj podmiot',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'nsf6m3j2': {
      'en':
          'Wprowadź nazwę podmiotu z oficjalnej listy lub wprowadź adres strony internetowej aby rozpocząć analizę zgodności',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'ezj2hfjl': {
      'en': 'Wybierz podmiot z listy MF',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'iavw5cj3': {
      'en': 'Wybierz...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '1swpykcg': {
      'en': 'Search...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'gvat3uc9': {
      'en': 'eZaklady',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '39cax0l1': {
      'en': 'HackNation Bet',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'xembfd1o': {
      'en': 'Podaj adres strony internetowej',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '9qa2kbcq': {
      'en': 'Adres strony internetowej',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '9yy1kduq': {
      'en': 'Tryb penego skanowania / szybki skan',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'jvqhkh2v': {
      'en': 'Rozpocznij teraz',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '0n0guyat': {
      'en': 'Pokaż ostatnie wyniki',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'aiwlte5d': {
      'en': 'Oferta vs Regulamin',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'pdmy8jg8': {
      'en': 'Linki do innych domen',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'ijx8klue': {
      'en': 'Historia zmian',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'abwpuswq': {
      'en': 'Technologie strony',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '95ej1cjd': {
      'en': 'Certyfikat SSL',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'a11kyxon': {
      'en': 'Geolokalizacja serwerów',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'y8a0fldk': {
      'en': 'Integracje płatności',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '8nnmv998': {
      'en': 'Ostatnio skanowane',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'azzagle8': {
      'en': 'Nazwa podmiotu',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'rg82d77p': {
      'en': 'WWW',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '17bnycuh': {
      'en': 'Ostatni skan',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'by012g8l': {
      'en': 'Alerty',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'dnqq1ai2': {
      'en': 'Z Listy MF',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '6xp2u5ox': {
      'en': 'Zgodność: Wymaga Uwagi',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'pvd1xwby': {
      'en': '23',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '8c2aij5y': {
      'en': 'Liczba\nZnalezionych Gier',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '1gi7d3w7': {
      'en': '4',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'dg1qu2qw': {
      'en': 'Niezgodne\nKategorie',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'yf4okc5y': {
      'en': '7',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'vv7sbnvm': {
      'en': 'Podejrzane\nLinki',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'bbfafxp2': {
      'en': 'Oferta vs Regulamin',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '3sctngvh': {
      'en': 'Regulamin / zezwolenie',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '683mlr3q': {
      'en': 'Zakłady Naziemne',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'kvdor9fm': {
      'en': 'Zakłady Internetowe',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'eaggd31d': {
      'en': 'Zakłady Live',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'zgytsbde': {
      'en': 'Rzeczywista oferta',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'nmmbfxcu': {
      'en': 'Zakłady Naziemne',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'vl0my1np': {
      'en': 'Zakłady Internetowe',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'btlxgddq': {
      'en': 'Zakłady Live',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'i4enl970': {
      'en': 'Analiza ruchu',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'e5xb080i': {
      'en': 'Czas',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '1o03tmdf': {
      'en': 'Treść reklamy (URL)',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'kxz0l82q': {
      'en': 'Status',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'o4hp0lxf': {
      'en': 'Źródło',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '7xxxkryx': {
      'en': 'Zrzut ekranu',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'b4kxjxhm': {
      'en': 'Oś czasu zmain',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'i7p2ezeu': {
      'en': 'Szczegóły techniczne',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'by4tojao': {
      'en':
          '=== WebScan Report v1.8 (Windows Diagnostic Mode) ===\nTarget URL: https://hacknationbet.pl\nScan Timestamp: 2025-01-14 12:44:22\n\n[DNS LOOKUP]\n - Hostname: luckyspin-casino.net\n - IPv4: 185.233.41.92\n - TTL: 260s\n - Registrar: NameCheap Inc.\n\n[HTTP CHECK]\n - Status: 200 OK\n - Server: nginx/1.22.1\n - Compression: gzip enabled\n - TLS Version: TLS 1.3\n - Cert Issuer: Let\'s Encrypt Authority X3\n - Cert Exp: 2025-04-09\n\n[SECURITY HEADERS]\n - HSTS: enabled (max-age=15552000)\n - CSP: missing\n - X-Frame-Options: SAMEORIGIN\n - X-XSS-Protection: disabled\n\n[PORT SCAN - REMOTE]\n - 80/tcp: open  (HTTP)\n - 443/tcp: open (HTTPS)\n - 2083/tcp: filtered (cPanel SSL)\n - 3306/tcp: closed (MySQL)\n\n[SITE TECHNOLOGIES]\n - Backend: PHP 8.1.13\n - Framework: Laravel 10.x\n - Frontend: React 18 + TailwindCSS\n - DB Engine: MariaDB 10.6\n - Cookie Tracking: Enabled (session + analytics)\n - Payment Provider API: detected (masked)\n\n[PERFORMANCE]\n - Response time: 184 ms\n - Page weight: 3.2 MB\n - Active scripts: 17\n - External CDNs: Cloudflare, jsDelivr\n\n[THREATS & FLAGS]\n - High-Risk Category: Gambling / Betting\n - Suspicious JS Inject: none detected\n - Malware signatures: 0\n - Geo restrictions: none\n\n=== END OF REPORT ===\n',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '1chfaq2t': {
      'en': 'Wykryte niezgodności',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '271hq2b7': {
      'en': 'Porównanie stawek',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '9d9769us': {
      'en': 'System Monitorowania Zakładów Wzajemnych',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'vz4iyeis': {
      'en': 'Grzegorz Mazurkiewicz',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '1mwilmis': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
  // Waiting
  {
    'hfh8iwf3': {
      'en': 'Proszę czekać',
      'ar': 'هل أنت متأكد أنك تريد حذف حسابك؟',
      'de': 'Möchten Sie Ihr Konto wirklich löschen?',
      'es': '¿Estás seguro de que deseas eliminar tu cuenta?',
      'fr': 'Êtes-vous sûr de vouloir\nsupprimer votre compte ?',
      'gu': 'શું તમે ખરેખર તમારું એકાઉન્ટ કાઢી નાખવા માંગો છો?',
      'hi': 'क्या आप इस खाते को हटाने के लिए सुनिश्चित हैं?',
      'ja': '本当にアカウントを削除してもよろしいですか？',
      'ru': 'Вы уверены, что хотите\nудалить свою учетную запись?',
      'zh_Hant': '您確定要\n刪除您的帳戶嗎？',
    },
    '06g14pwr': {
      'en': 'Trwa skanowanie',
      'ar': 'هل أنت متأكد أنك تريد حذف حسابك؟',
      'de': 'Möchten Sie Ihr Konto wirklich löschen?',
      'es': '¿Estás seguro de que deseas eliminar tu cuenta?',
      'fr': 'Êtes-vous sûr de vouloir\nsupprimer votre compte ?',
      'gu': 'શું તમે ખરેખર તમારું એકાઉન્ટ કાઢી નાખવા માંગો છો?',
      'hi': 'क्या आप इस खाते को हटाने के लिए सुनिश्चित हैं?',
      'ja': '本当にアカウントを削除してもよろしいですか？',
      'ru': 'Вы уверены, что хотите\nудалить свою учетную запись?',
      'zh_Hant': '您確定要\n刪除您的帳戶嗎？',
    },
  },
  // Miscellaneous
  {
    '5wajhq5p': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'ebv7wgq3': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'no9si425': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'dmw2ewet': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'bomziphd': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'zlulrwge': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'lpp6otpe': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'em86ccgu': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'o0r1zeoz': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'em92rzvb': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'rgm8urca': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'pshwtjam': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '2433bgkv': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'ap09bqp9': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'w6u2zmbo': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'y8f5z1zo': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'jv30bwbn': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'r4wxy21l': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '1ecvzfng': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'qhrn3ugq': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'teh3xl7a': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '685fay6p': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '1y7qy7ew': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'tyzxfdfy': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'yly22bw2': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    '0mdowe7b': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
    'vyba20tv': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'gu': '',
      'hi': '',
      'ja': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
].reduce((a, b) => a..addAll(b));
